### ISSUE TITLE
提示版本过低，运行了您的update脚本也是如此

### ISSUE THREAD

**Issue by DOCCA0** [bestwu/docker-qq#35] opened 2021-01-01 03:40 UTC
hi~,这是更新日志：

`➜  update sh run.sh 
[sudo] wu 的密码： 
qq
renamed '/entrypoint.sh' -> '/entrypoint.sh.bk'
renamed '/update.sh' -> '/entrypoint.sh'
qq
/entrypoint.sh: line 6: [: !=: unary operator expected
/entrypoint.sh: line 9: [: !=: unary operator expected
启动 QQ
realpath: missing operand
Try 'realpath --help' for more information.
2021年 01月 01日 星期五 19:08:01 UTC:Run Deepin-QQ 8.9.19983deepin23
2021年 01月 01日 星期五 19:08:01 UTC:run Deepin-QQ progress pid 

7-Zip [32] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,32 bits,4 CPUs Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (906E9),ASM,AES-NI)

Scanning the drive for archives:
1 file, 103108486 bytes (99 MiB)

Extracting archive: /opt/deepinwine/apps/Deepin-QQ/files.7z
--
Path = /opt/deepinwine/apps/Deepin-QQ/files.7z
Type = 7z
Physical Size = 103108486
Headers Size = 26282
Method = LZMA2:26 BCJ2
Solid = +
Blocks = 1

Everything is Ok

Folders: 768
Files: 2151
Size:       411712910
Compressed: 103108486
total 0
lrwxrwxrwx 1 qq qq 10 1月   1 19:08 c: -> ../drive_c
lrwxrwxrwx 1 qq qq 10 1月   1 19:08 com1 -> /dev/ttyS0
lrwxrwxrwx 1 qq qq 10 1月   1 19:08 com2 -> /dev/ttyS1
lrwxrwxrwx 1 qq qq 10 1月   1 19:08 com3 -> /dev/ttyS2
lrwxrwxrwx 1 qq qq 10 1月   1 19:08 com4 -> /dev/ttyS3
lrwxrwxrwx 1 qq qq  8 1月   1 19:08 lpt1 -> /dev/lp0
lrwxrwxrwx 1 qq qq  1 1月   1 19:08 z: -> /
2021年 01月 01日 星期五 19:08:07 UTC:CallApp Deepin-QQ  
2021年 01月 01日 星期五 19:08:07 UTC:kill QQ.exe block
2021年 01月 01日 星期五 19:08:07 UTC:No wine process found
2021年 01月 01日 星期五 19:08:07 UTC:start running...
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/home/qq/.deepinwine/Deepin-QQ' has been updated.
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Value in failed request:  0x1ef
  Serial number of failed request:  540
  Current serial number in output stream:  541
/entrypoint.sh: line 6: [: !=: unary operator expected
/entrypoint.sh: line 9: [: !=: unary operator expected
启动 QQ
realpath: missing operand
Try 'realpath --help' for more information.
2021年 01月 01日 星期五 19:08:47 UTC:Run Deepin-QQ 8.9.19983deepin23
2021年 01月 01日 星期五 19:08:47 UTC:run Deepin-QQ progress pid 
total 0
lrwxrwxrwx 1 qq qq 10 1月   1 19:08 c: -> ../drive_c
lrwxrwxrwx 1 qq qq  1 1月   1 19:08 z: -> /
2021年 01月 01日 星期五 19:08:47 UTC:CallApp Deepin-QQ  
2021年 01月 01日 星期五 19:08:47 UTC:kill QQ.exe block
2021年 01月 01日 星期五 19:08:47 UTC:No wine process found
2021年 01月 01日 星期五 19:08:47 UTC:start running...
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
wine: cannot find L"c:\\Program Files\\Tencent\\QQ\\Bin\\TXPlatform.exe"
init server success 127.0.0.1 12291
Ign:1 https://mirrors.aliyun.com/deepin stable InRelease
Err:2 https://mirrors.aliyun.com/deepin stable Release
  404  Not Found [IP: 113.142.161.240 443]
Reading package lists...
E: The repository 'https://mirrors.aliyun.com/deepin stable Release' does not have a Release file.
Reading package lists...
Building dependency tree...
Reading state information...
deepin.com.qq.im is already the newest version (8.9.19983deepin23).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
renamed '/entrypoint.sh.bk' -> '/entrypoint.sh'
/entrypoint.sh: line 6: [: !=: unary operator expected
/entrypoint.sh: line 9: [: !=: unary operator expected
启动 QQ
realpath: missing operand
Try 'realpath --help' for more information.
2021年 01月 01日 星期五 19:10:18 UTC:Run Deepin-QQ 8.9.19983deepin23
2021年 01月 01日 星期五 19:10:18 UTC:run Deepin-QQ progress pid 
total 0
lrwxrwxrwx 1 qq qq 10 1月   1 19:10 c: -> ../drive_c
lrwxrwxrwx 1 qq qq  1 1月   1 19:10 z: -> /
2021年 01月 01日 星期五 19:10:18 UTC:CallApp Deepin-QQ  
2021年 01月 01日 星期五 19:10:18 UTC:kill QQ.exe block
2021年 01月 01日 星期五 19:10:18 UTC:No wine process found
2021年 01月 01日 星期五 19:10:18 UTC:start running...
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
wine: cannot find L"c:\\Program Files\\Tencent\\QQ\\Bin\\TXPlatform.exe"
init server success 127.0.0.1 12291
Ign:1 https://mirrors.aliyun.com/deepin stable InRelease
Err:2 https://mirrors.aliyun.com/deepin stable Release
  404  Not Found [IP: 113.142.161.248 443]
Reading package lists...
E: The repository 'https://mirrors.aliyun.com/deepin stable Release' does not have a Release file.
Reading package lists...
Building dependency tree...
Reading state information...
deepin.com.qq.im is already the newest version (8.9.19983deepin23).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
renamed '/entrypoint.sh.bk' -> '/entrypoint.sh'
/entrypoint.sh: line 6: [: !=: unary operator expected
/entrypoint.sh: line 9: [: !=: unary operator expected
启动 QQ
realpath: missing operand
Try 'realpath --help' for more information.
2021年 01月 01日 星期五 19:14:12 UTC:Run Deepin-QQ 8.9.19983deepin23
2021年 01月 01日 星期五 19:14:12 UTC:run Deepin-QQ progress pid 
total 0
lrwxrwxrwx 1 qq qq 10 1月   1 19:14 c: -> ../drive_c
lrwxrwxrwx 1 qq qq  1 1月   1 19:14 z: -> /
2021年 01月 01日 星期五 19:14:12 UTC:CallApp Deepin-QQ  
2021年 01月 01日 星期五 19:14:12 UTC:kill QQ.exe block
2021年 01月 01日 星期五 19:14:12 UTC:No wine process found
2021年 01月 01日 星期五 19:14:12 UTC:start running...
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
wine: cannot find L"c:\\Program Files\\Tencent\\QQ\\Bin\\TXPlatform.exe"
init server success 127.0.0.1 12291
退出
/entrypoint.sh: line 6: [: !=: unary operator expected
/entrypoint.sh: line 9: [: !=: unary operator expected
启动 QQ
realpath: missing operand
Try 'realpath --help' for more information.
2021年 01月 01日 星期五 19:22:49 UTC:Run Deepin-QQ 8.9.19983deepin23
2021年 01月 01日 星期五 19:22:49 UTC:run Deepin-QQ progress pid 
total 0
lrwxrwxrwx 1 qq qq 10 1月   1 19:22 c: -> ../drive_c
lrwxrwxrwx 1 qq qq  1 1月   1 19:22 z: -> /
2021年 01月 01日 星期五 19:22:49 UTC:CallApp Deepin-QQ  
2021年 01月 01日 星期五 19:22:49 UTC:kill QQ.exe block
2021年 01月 01日 星期五 19:22:49 UTC:No wine process found
2021年 01月 01日 星期五 19:22:49 UTC:start running...
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
wine: cannot find L"c:\\Program Files\\Tencent\\QQ\\Bin\\TXPlatform.exe"
init server success 127.0.0.1 12291
Ign:1 https://mirrors.aliyun.com/deepin stable InRelease
Err:2 https://mirrors.aliyun.com/deepin stable Release
  404  Not Found [IP: 113.137.53.178 443]
Reading package lists...
E: The repository 'https://mirrors.aliyun.com/deepin stable Release' does not have a Release file.
Reading package lists...
Building dependency tree...
Reading state information...
deepin.com.qq.im is already the newest version (8.9.19983deepin23).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
renamed '/entrypoint.sh.bk' -> '/entrypoint.sh'
/entrypoint.sh: line 6: [: !=: unary operator expected
/entrypoint.sh: line 9: [: !=: unary operator expected
启动 QQ
realpath: missing operand
Try 'realpath --help' for more information.
2021年 01月 01日 星期五 19:23:28 UTC:Run Deepin-QQ 8.9.19983deepin23
2021年 01月 01日 星期五 19:23:28 UTC:run Deepin-QQ progress pid 
total 0
lrwxrwxrwx 1 qq qq 10 1月   1 19:23 c: -> ../drive_c
lrwxrwxrwx 1 qq qq  1 1月   1 19:23 z: -> /
2021年 01月 01日 星期五 19:23:28 UTC:CallApp Deepin-QQ  
2021年 01月 01日 星期五 19:23:28 UTC:kill QQ.exe block
2021年 01月 01日 星期五 19:23:28 UTC:No wine process found
2021年 01月 01日 星期五 19:23:28 UTC:start running...
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
wine: cannot find L"c:\\Program Files\\Tencent\\QQ\\Bin\\TXPlatform.exe"
init server success 127.0.0.1 12291
Ign:1 https://mirrors.aliyun.com/deepin stable InRelease
Err:2 https://mirrors.aliyun.com/deepin stable Release
  404  Not Found [IP: 113.137.53.178 443]
Reading package lists...
E: The repository 'https://mirrors.aliyun.com/deepin stable Release' does not have a Release file.
Reading package lists...
Building dependency tree...
Reading state information...
deepin.com.qq.im is already the newest version (8.9.19983deepin23).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
renamed '/entrypoint.sh.bk' -> '/entrypoint.sh'
/entrypoint.sh: line 6: [: !=: unary operator expected
/entrypoint.sh: line 9: [: !=: unary operator expected
启动 QQ
realpath: missing operand
Try 'realpath --help' for more information.
2021年 01月 01日 星期五 19:28:28 UTC:Run Deepin-QQ 8.9.19983deepin23
2021年 01月 01日 星期五 19:28:28 UTC:run Deepin-QQ progress pid 
total 0
lrwxrwxrwx 1 qq qq 10 1月   1 19:28 c: -> ../drive_c
lrwxrwxrwx 1 qq qq  1 1月   1 19:28 z: -> /
2021年 01月 01日 星期五 19:28:28 UTC:CallApp Deepin-QQ  
2021年 01月 01日 星期五 19:28:28 UTC:kill QQ.exe block
2021年 01月 01日 星期五 19:28:28 UTC:No wine process found
2021年 01月 01日 星期五 19:28:28 UTC:start running...
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
wine: cannot find L"c:\\Program Files\\Tencent\\QQ\\Bin\\TXPlatform.exe"
init server success 127.0.0.1 12291
Ign:1 https://mirrors.aliyun.com/deepin stable InRelease
Err:2 https://mirrors.aliyun.com/deepin stable Release
  404  Not Found [IP: 113.137.53.178 443]
Reading package lists...
E: The repository 'https://mirrors.aliyun.com/deepin stable Release' does not have a Release file.
Reading package lists...
Building dependency tree...
Reading state information...
deepin.com.qq.im is already the newest version (8.9.19983deepin23).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
renamed '/entrypoint.sh.bk' -> '/entrypoint.sh'
/entrypoint.sh: line 6: [: !=: unary operator expected
/entrypoint.sh: line 9: [: !=: unary operator expected
启动 QQ
realpath: missing operand
Try 'realpath --help' for more information.
2021年 01月 01日 星期五 19:32:15 UTC:Run Deepin-QQ 8.9.19983deepin23
2021年 01月 01日 星期五 19:32:15 UTC:run Deepin-QQ progress pid 
total 0
lrwxrwxrwx 1 qq qq 10 1月   1 19:32 c: -> ../drive_c
lrwxrwxrwx 1 qq qq  1 1月   1 19:32 z: -> /
2021年 01月 01日 星期五 19:32:15 UTC:CallApp Deepin-QQ  
2021年 01月 01日 星期五 19:32:15 UTC:kill QQ.exe block
2021年 01月 01日 星期五 19:32:15 UTC:No wine process found
2021年 01月 01日 星期五 19:32:15 UTC:start running...
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
wine: cannot find L"c:\\Program Files\\Tencent\\QQ\\Bin\\TXPlatform.exe"
init server success 127.0.0.1 12291
退出
/entrypoint.sh: line 6: [: !=: unary operator expected
/entrypoint.sh: line 9: [: !=: unary operator expected
启动 QQ
realpath: missing operand
Try 'realpath --help' for more information.
2021年 01月 01日 星期五 19:38:29 UTC:Run Deepin-QQ 8.9.19983deepin23
2021年 01月 01日 星期五 19:38:29 UTC:run Deepin-QQ progress pid 
total 0
lrwxrwxrwx 1 qq qq 10 1月   1 19:38 c: -> ../drive_c
lrwxrwxrwx 1 qq qq  1 1月   1 19:38 z: -> /
2021年 01月 01日 星期五 19:38:29 UTC:CallApp Deepin-QQ  
2021年 01月 01日 星期五 19:38:30 UTC:kill QQ.exe block
2021年 01月 01日 星期五 19:38:30 UTC:No wine process found
2021年 01月 01日 星期五 19:38:30 UTC:start running...
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
wine: cannot find L"c:\\Program Files\\Tencent\\QQ\\Bin\\TXPlatform.exe"
Ign:1 https://mirrors.aliyun.com/deepin stable InRelease
Err:2 https://mirrors.aliyun.com/deepin stable Release
  404  Not Found [IP: 124.115.10.236 443]
Reading package lists...
E: The repository 'https://mirrors.aliyun.com/deepin stable Release' does not have a Release file.
Reading package lists...
Building dependency tree...
Reading state information...
deepin.com.qq.im is already the newest version (8.9.19983deepin23).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
renamed '/entrypoint.sh.bk' -> '/entrypoint.sh'
qq
`

**Comment by zhengdangdang** [comment] 2021-01-06 12:52
我跟你的情况一样。也是。b站上有视频演示，他运行脚本能够成功，我看了下，信息输出里面的不同之处是：0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
人家是有更新的，咱们这个数量都是0

**Comment by top-bettercode** [comment] 2021-01-07 01:56
Duplicate of #27 
镜像已更新最新软件包，使用 docker pull bestwu/qq:im 更新本地镜像后，重新运行

**Closed as completed** 2021-01-07 05:12 UTC
